import streamlit as st
import pandas as pd
import sqlite3
from crewai import Agent, Task, Crew, Process
from langchain_community.llms import Ollama

# 1. Page Configuration
st.set_page_config(page_title="Agentic Data Intelligence Network", layout="wide")
st.title("Autonomous Multi-Agent Data Intelligence Network 🤖📊")
st.caption("Powered by Local LLM Orchestration & Self-Healing Critic Loops")

# 2. Local Relational Database Initialization
@st.cache_resource
def init_portfolio_db():
    conn = sqlite3.connect("crop_intelligence.db", check_same_thread=False)
    cursor = conn.cursor()
    
    # Structural Crop Production Matrix Schema
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS crop_yields (
            record_id INTEGER PRIMARY KEY AUTOINCREMENT,
            crop_name TEXT,
            region TEXT,
            rainfall_required INTEGER,
            fertilizer_used TEXT,
            yield_mt INTEGER
        )
    """)
    
    # Populate mock analytics data if table is completely fresh
    cursor.execute("SELECT COUNT(*) FROM crop_yields")
    if cursor.fetchone()[0] == 0:
        mock_data = [
            ('Wheat', 'North', 80, 'Yes', 4500),
            ('Rice', 'South', 200, 'Yes', 6200),
            ('Maize', 'West', 120, 'No', 3100),
            ('Barley', 'North', 90, 'No', 2800),
            ('Sugarcane', 'East', 250, 'Yes', 8900)
        ]
        cursor.executemany("INSERT INTO crop_yields (crop_name, region, rainfall_required, fertilizer_used, yield_mt) VALUES (?, ?, ?, ?, ?)", mock_data)
        conn.commit()
    return conn

db_conn = init_portfolio_db()

# Display active database structural baseline parameters to user
st.subheader("📋 Underlying Enterprise Database Context")
df_preview = pd.read_sql_query("SELECT * FROM crop_yields", db_conn)
st.dataframe(df_preview, use_container_width=True, hide_index=True)
st.markdown("---")

# 3. Native Agentic Orchestration Layer
def run_agentic_pipeline(user_prompt):
    # Connect directly to local open-source model running via Ollama framework
    local_llm = Ollama(model="llama3")
    
    # Structural DB Schema instructions injected into Agent Context
    db_schema_context = """
    Table Name: crop_yields
    Columns:
    - crop_name (TEXT)
    - region (TEXT)
    - rainfall_required (INTEGER)
    - fertilizer_used (TEXT)
    - yield_mt (INTEGER)
    """

    # Agent 1: The Expert SQL Database Engineer
    sql_developer = Agent(
        role="Senior SQL Developer",
        goal="Translate plain English requests into highly optimized, valid SQLite syntax.",
        backstory="You are an expert database administrator. You strictly write clean SQL queries based on provided schemas, wrapping queries inside clear ```sql tags.",
        verbose=True,
        llm=local_llm
    )

    # Agent 2: The Critical Data Analyst & Error Validator
    data_critic = Agent(
        role="Data Integrity Critic",
        goal="Analyze generated SQL queries for accuracy, syntax faults, or performance regressions.",
        backstory="You audit code. You review the SQL generated by the developer, cross-reference it with the schema, and either approve it or specify modifications to avoid runtime database evaluation crashes.",
        verbose=True,
        llm=local_llm
    )

    # Define Sequence Tasks
    task_write_sql = Task(
        description=f"Convert this prompt: '{user_prompt}' into a SQL query. Database Schema Context:\n{db_schema_context}",
        expected_output="A single valid SQLite string wrapped strictly in ```sql ... ``` code blocks.",
        agent=sql_developer
    )

    task_audit_sql = Task(
        description="Verify the generated SQL query for structural flaws or syntax errors against the schema rules.",
        expected_output="The finalized, verified clean SQL statement ready for live database execution.",
        agent=data_critic
    )

    # Spin up the Crew Engine Team
    analysis_crew = Crew(
        agents=[sql_developer, data_critic],
        tasks=[task_write_sql, task_audit_sql],
        process=Process.sequential
    )

    raw_output = analysis_crew.kickoff()
    
    # Extract clean SQL string using regular expression parser
    sql_match = re.search(r"```sql\n(.*?)```", raw_output, re.DOTALL)
    executable_sql = sql_match.group(1).strip() if sql_match else str(raw_output).strip()
    return executable_sql

# 4. Interactive User Controls Split
col1, col2 = st.columns([1, 1])

with col1:
    st.subheader("Autonomous Execution Input")
    user_query = st.text_input("Ask anything regarding the metrics layout above:", placeholder="Which region has the lowest rainfall?")
    launch_pipeline = st.button("Kickoff Multi-Agent Crew", type="primary")

with col2:
    st.subheader("Agent Execution Analytics")
    if launch_pipeline:
        if not user_query.strip():
            st.warning("Please type an input query parameter.")
        else:
            with st.spinner("Crew Agents are actively negotiating pipeline tasks..."):
                try:
                    # Run generative multi-agent workflow process
                    compiled_query = run_agentic_pipeline(user_query)
                    
                    st.markdown("### Approved Agent SQL Output")
                    st.code(compiled_query, language="sql")
                    
                    # Execute on local schema
                    execution_results = pd.read_sql_query(compiled_query, db_conn)
                    st.markdown("### Executed Database Output Matrix")
                    st.dataframe(execution_results, use_container_width=True)
                    
                except Exception as e:
                    st.error(f"Agentic Pipeline Runtime Fault: {str(e)}")